"""PR Manager for AutoDev - handles PR creation and merging."""
from typing import Dict, Any, List, Optional
from core.github_client import GitHubClient
from utils.logger import get_logger


class PRManager:
    """
    Handles pull request creation, review, and merging.
    
    Responsibilities:
    - Create PRs with proper descriptions
    - Add reviewers
    - Check CI status
    - Auto-merge when ready
    - Handle merge conflicts
    """
    
    def __init__(self, github_client: GitHubClient, config: Optional[Dict[str, Any]] = None):
        self.github = github_client
        self.config = config or {}
        self.logger = get_logger("autodev.pr")
    
    def create_pr(
        self,
        branch: str,
        base: str = "main",
        title: Optional[str] = None,
        body: Optional[str] = None,
        reviewers: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Create a pull request.
        
        Args:
            branch: Source branch
            base: Target branch
            title: PR title
            body: PR body/description
            reviewers: List of reviewer usernames
            
        Returns:
            PR object from GitHub API
        """
        # Generate title if not provided
        if not title:
            title = f"AutoDev: {branch}"
        
        # Generate body if not provided
        if not body:
            body = self._generate_default_body(branch)
        
        self.logger.info(f"Creating PR: {title}")
        
        # Create PR
        pr = self.github.create_pull_request(
            title=title,
            body=body,
            head=branch,
            base=base
        )
        
        # Add reviewers if specified
        reviewers = reviewers or self.config.get("github", {}).get("add_reviewers", [])
        if reviewers:
            try:
                self.github.add_pr_reviewers(pr["number"], reviewers)
                self.logger.info(f"Added reviewers: {reviewers}")
            except Exception as e:
                self.logger.warning(f"Failed to add reviewers: {e}")
        
        return pr
    
    def _generate_default_body(self, branch: str) -> str:
        """Generate default PR body."""
        return f"""## AutoDev Generated PR

**Branch:** {branch}

### Summary
This PR was automatically generated by AutoDev.

### Changes
- See commit history for details

### Testing
- [ ] Tests pass
- [ ] Code follows project conventions

---
*Generated by AutoDev*
"""
    
    def check_pr_status(self, pr_number: int) -> Dict[str, Any]:
        """
        Check the status of a PR.
        
        Returns:
            Dict with status info (mergeable, checks passing, etc.)
        """
        pr = self.github.get_pull_request(pr_number)
        
        status = {
            "number": pr["number"],
            "title": pr["title"],
            "state": pr["state"],
            "mergeable": pr.get("mergeable"),
            "mergeable_state": pr.get("mergeable_state"),
            "draft": pr.get("draft", False),
            "commits": pr["commits"],
            "additions": pr.get("additions", 0),
            "deletions": pr.get("deletions", 0)
        }
        
        # Check if mergeable
        if pr.get("mergeable") is False:
            status["reason"] = "Merge conflicts exist"
        elif pr.get("mergeable") is True and pr.get("mergeable_state") == "clean":
            status["ready_to_merge"] = True
        else:
            status["ready_to_merge"] = False
        
        return status
    
    def merge_pr(
        self,
        pr_number: int,
        commit_message: str = ""
    ) -> Dict[str, Any]:
        """
        Merge a pull request.
        
        Args:
            pr_number: PR number
            commit_message: Optional commit message
            
        Returns:
            Merge result from GitHub API
        """
        # Check status first
        status = self.check_pr_status(pr_number)
        
        if not status.get("ready_to_merge"):
            raise RuntimeError(f"PR {pr_number} is not ready to merge: {status.get('reason', 'unknown')}")
        
        self.logger.info(f"Merging PR #{pr_number}")
        
        result = self.github.merge_pr(pr_number, commit_message)
        
        self.logger.info(f"PR #{pr_number} merged")
        return result
    
    def add_comment(self, pr_number: int, comment: str):
        """Add a comment to a PR."""
        # GitHubClient doesn't have add_comment, would need to add it
        self.logger.info(f"Would add comment to PR #{pr_number}: {comment[:50]}...")
    
    def get_check_runs(self, pr_number: int) -> List[Dict[str, Any]]:
        """
        Get check runs (CI status) for a PR.
        
        Note: Would need additional GitHub API implementation
        """
        pr = self.github.get_pull_request(pr_number)
        
        # This would need to call GitHub's checks API
        # For now, return placeholder
        return []
    
    def wait_for_checks(
        self,
        pr_number: int,
        timeout: int = 300,
        check_interval: int = 10
    ) -> bool:
        """
        Wait for all CI checks to pass.
        
        Args:
            pr_number: PR number
            timeout: Max wait time in seconds
            check_interval: How often to check
            
        Returns:
            True if all checks pass, False if timeout
        """
        import time
        
        elapsed = 0
        while elapsed < timeout:
            status = self.check_pr_status(pr_number)
            
            if status.get("ready_to_merge"):
                return True
            
            if status.get("state") == "closed":
                return False
            
            time.sleep(check_interval)
            elapsed += check_interval
        
        self.logger.warning(f"Timeout waiting for checks on PR #{pr_number}")
        return False
