"""PR Manager for AutoDev - handles PR creation and merging."""
import time
from typing import Dict, Any, List, Optional
from core.github_client import GitHubClient
from utils.logger import get_logger

# Import reviewer for agent-to-agent review
try:
    from agents.reviewer.agent import ReviewerAgent, ReviewLoop
    REVIEWER_AVAILABLE = True
except ImportError:
    REVIEWER_AVAILABLE = False
    ReviewerAgent = None
    ReviewLoop = None


class PRManager:
    """
    Handles pull request creation, review, and merging.
    
    Responsibilities:
    - Create PRs with proper descriptions
    - Add reviewers
    - Check CI status
    - Auto-merge when ready
    - Handle merge conflicts
    """
    
    def __init__(self, github_client: GitHubClient, config: Optional[Dict[str, Any]] = None):
        self.github = github_client
        self.config = config or {}
        self.logger = get_logger("autodev.pr")
    
    def create_pr(
        self,
        branch: str,
        base: str = "main",
        title: Optional[str] = None,
        body: Optional[str] = None,
        reviewers: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Create a pull request.
        
        Args:
            branch: Source branch
            base: Target branch
            title: PR title
            body: PR body/description
            reviewers: List of reviewer usernames
            
        Returns:
            PR object from GitHub API
        """
        # Generate title if not provided
        if not title:
            title = f"AutoDev: {branch}"
        
        # Generate body if not provided
        if not body:
            body = self._generate_default_body(branch)
        
        self.logger.info(f"Creating PR: {title}")
        
        # Create PR
        pr = self.github.create_pull_request(
            title=title,
            body=body,
            head=branch,
            base=base
        )
        
        # Add reviewers if specified
        reviewers = reviewers or self.config.get("github", {}).get("add_reviewers", [])
        if reviewers:
            try:
                self.github.add_pr_reviewers(pr["number"], reviewers)
                self.logger.info(f"Added reviewers: {reviewers}")
            except Exception as e:
                self.logger.warning(f"Failed to add reviewers: {e}")
        
        return pr
    
    def _generate_default_body(self, branch: str) -> str:
        """Generate default PR body."""
        return f"""## AutoDev Generated PR

**Branch:** {branch}

### Summary
This PR was automatically generated by AutoDev.

### Changes
- See commit history for details

### Testing
- [ ] Tests pass
- [ ] Code follows project conventions

---
*Generated by AutoDev*
"""
    
    def check_pr_status(self, pr_number: int) -> Dict[str, Any]:
        """
        Check the status of a PR.
        
        Returns:
            Dict with status info (mergeable, checks passing, etc.)
        """
        pr = self.github.get_pull_request(pr_number)
        
        status = {
            "number": pr["number"],
            "title": pr["title"],
            "state": pr["state"],
            "mergeable": pr.get("mergeable"),
            "mergeable_state": pr.get("mergeable_state"),
            "draft": pr.get("draft", False),
            "commits": pr.get("commits", 0),
            "additions": pr.get("additions", 0),
            "deletions": pr.get("deletions", 0)
        }
        
        # Check if mergeable - handle all states
        if pr.get("mergeable") is False:
            status["reason"] = "Merge conflicts exist"
            status["ready_to_merge"] = False
        elif pr.get("mergeable") is True:
            # Check for clean/unstable states (green or yellow CI is ok)
            mergeable_state = pr.get("mergeable_state", "")
            if mergeable_state in ("clean", "unstable", "has_hooks"):
                status["ready_to_merge"] = True
            else:
                status["ready_to_merge"] = False
                status["reason"] = f"Mergeable state: {mergeable_state}"
        else:
            status["ready_to_merge"] = False
            status["reason"] = "Not mergeable"
        
        return status
    
    def merge_pr(
        self,
        pr_number: int,
        commit_message: str = ""
    ) -> Dict[str, Any]:
        """
        Merge a pull request.
        
        Args:
            pr_number: PR number
            commit_message: Optional commit message
            
        Returns:
            Merge result from GitHub API
        """
        # Check status first
        status = self.check_pr_status(pr_number)
        
        if not status.get("ready_to_merge"):
            raise RuntimeError(f"PR {pr_number} is not ready to merge: {status.get('reason', 'unknown')}")
        
        self.logger.info(f"Merging PR #{pr_number}")
        
        result = self.github.merge_pr(pr_number, commit_message)
        
        self.logger.info(f"PR #{pr_number} merged")
        return result
    
    def add_comment(self, pr_number: int, comment: str):
        """Add a comment to a PR."""
        # GitHubClient doesn't have add_comment, would need to add it
        self.logger.info(f"Would add comment to PR #{pr_number}: {comment[:50]}...")
    
    def get_check_runs(self, pr_number: int) -> List[Dict[str, Any]]:
        """
        Get check runs (CI status) for a PR.
        
        Returns list of check runs with their status.
        """
        try:
            # Get the PR to find head SHA
            pr = self.github.get_pull_request(pr_number)
            head_sha = pr.get("head", {}).get("sha")
            
            if not head_sha:
                return []
            
            # Get check runs for the commit
            # This would need GitHubClient to have a get_check_runs method
            # For now, return status from PR mergeable_state
            return [{
                "name": "GitHub PR Checks",
                "status": "completed",
                "conclusion": "success" if pr.get("mergeable") else "failure"
            }]
        except Exception as e:
            self.logger.error(f"Failed to get check runs: {e}")
            return []
    
    def wait_for_checks(
        self,
        pr_number: int,
        timeout: int = 300,
        check_interval: int = 10
    ) -> bool:
        """
        Wait for all CI checks to pass.
        
        Args:
            pr_number: PR number
            timeout: Max wait time in seconds
            check_interval: How often to check
            
        Returns:
            True if all checks pass, False if timeout
        """
        elapsed = 0
        while elapsed < timeout:
            status = self.check_pr_status(pr_number)
            
            if status.get("ready_to_merge"):
                return True
            
            if status.get("state") == "closed":
                return False
            
            time.sleep(check_interval)
            elapsed += check_interval
        
        self.logger.warning(f"Timeout waiting for checks on PR #{pr_number}")
        return False
    
    def auto_review_and_merge(
        self,
        pr_number: int,
        repo_path: str,
        branch: str,
        base: str = "main",
        max_review_iterations: int = 3,
        wait_for_ci: bool = True,
        ci_timeout: int = 300
    ) -> Dict[str, Any]:
        """
        Run agent-to-agent review and optionally merge.
        
        This is the key method for harness engineering:
        1. Reviewer agent reviews the PR
        2. If issues found → iterate with fixes
        3. If approved → wait for CI → merge
        
        Args:
            pr_number: PR number
            repo_path: Local repo path
            branch: Branch being reviewed
            base: Base branch
            max_review_iterations: Max review/fix cycles
            wait_for_ci: Whether to wait for CI checks
            ci_timeout: Timeout for CI in seconds
            
        Returns:
            Dict with status, review results, and merge result
        """
        if not REVIEWER_AVAILABLE:
            self.logger.warning("Reviewer agent not available, skipping review")
            return {"status": "skipped", "reason": "reviewer_not_available"}
        
        self.logger.info(f"🤖 Starting agent-to-agent review for PR #{pr_number}")
        
        # Run the review loop
        reviewer = ReviewerAgent(config=self.config)
        review_loop = ReviewLoop(config=self.config)
        
        # Run review
        review_result = review_loop.run_review_loop(
            repo_path=repo_path,
            branch=branch,
            base=base,
            on_fix_callback=None  # Could hook into coder agent here
        )
        
        if review_result["status"] != "approved":
            self.logger.warning(f"Review not approved: {review_result}")
            return {
                "status": "review_failed",
                "iterations": review_result["iterations"],
                "issues": review_result["issues"]
            }
        
        self.logger.info("✅ Review approved!")
        
        # Wait for CI if requested
        if wait_for_ci:
            self.logger.info("⏳ Waiting for CI checks...")
            
            ci_passed = self.wait_for_checks(pr_number, timeout=ci_timeout)
            
            if not ci_passed:
                self.logger.warning("CI checks did not pass")
                return {
                    "status": "ci_failed",
                    "review_status": "approved"
                }
            
            self.logger.info("✅ CI checks passed!")
        
        # Merge
        try:
            merge_result = self.merge_pr(
                pr_number,
                commit_message=f"AutoDev: Merge {branch}"
            )
            
            self.logger.info(f"🎉 PR #{pr_number} merged!")
            return {
                "status": "merged",
                "review_status": "approved",
                "merge_commit": merge_result.get("sha")
            }
            
        except Exception as e:
            self.logger.error(f"Failed to merge: {e}")
            return {
                "status": "merge_failed",
                "review_status": "approved",
                "error": str(e)
            }
